---
language: python
services: docker
branches:
  only: main
jobs:
  include:
    - name: (Alpine Linux/CentOS/Debian/Ubuntu) Cleanup config and try to install modules
      env:
        scenario: cleanup_module
    - name: (Alpine Linux/CentOS/Debian/Ubuntu) Test config generation
      env:
        scenario: default
    - name: (CentOS/Debian/Ubuntu) Test config generation with NGINX Plus directives
      if: env(NGINX_CRT) is present and env(NGINX_KEY) is present
      env:
        scenario: plus
    - name: (Alpine Linux/CentOS/Debian/Ubuntu) Install stable branch and push a config
      env:
        scenario: stable_push
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
install:
  - pip install ansible==2.9.13
  - pip install ansible-lint==4.3.5
  - pip install yamllint==1.24.2
  - pip install molecule==3.0.8
  - pip install docker==4.3.1
script:
  - molecule --version
  - ansible --version
  - travis_wait 50 molecule test -s $scenario
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
