---
- name: Converge
  hosts: all
  tasks:
    - name: Configure NGINX
      include_role:
        name: ansible-role-nginx-config
      vars:
        nginx_config_debug_output: true

        nginx_branch: stable
        nginx_config_main_upload_enable: true
        nginx_config_main_upload_src: ../files/nginx.conf
        nginx_config_http_upload_enable: true
        nginx_config_http_upload_src: ../files/http/*.conf
