---
- name: Ensure HTML directory exists
  ansible.builtin.file:
    path: "{{ item.deployment_location | default('/usr/share/nginx/html') | dirname }}"
    state: directory
    mode: 0755
  loop: "{{ nginx_config_html_demo_template }}"
  when: nginx_config_html_demo_template_enable | bool

- name: Dynamically generate HTML files
  ansible.builtin.template:
    src: "{{ item.template_file | default('www/index.html.j2') }}"
    dest: "{{ item.deployment_location | default('/usr/share/nginx/html/index.html') }}"
    backup: "{{ item.backup  | default(true) }}"
    mode: 0644
  loop: "{{ nginx_config_html_demo_template }}"
  when: nginx_config_html_demo_template_enable | bool

- name: Configure NGINX modules
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: BOF
    line: "load_module {{ item }};"
  loop: "{{ nginx_config_modules }}"
  when:
    - nginx_config_modules is defined
    - nginx_config_modules | length > 0
  notify: (Handler - NGINX Config) Run NGINX

- name: Ensure NGINX main directory exists
  ansible.builtin.file:
    path: "{{ nginx_config_main_template.deployment_location | default('/etc/nginx') | dirname }}"
    state: directory
    mode: 0755
  when: nginx_config_main_template_enable | bool

- name: Dynamically generate NGINX main configuration file
  ansible.builtin.template:
    src: "{{ nginx_config_main_template.template_file | default('nginx.conf.j2') }}"
    dest: "{{ nginx_config_main_template.deployment_location | default('/etc/nginx/nginx.conf') }}"
    backup: "{{ nginx_config_main_template.backup  | default(true) }}"
    mode: 0644
  when: nginx_config_main_template_enable | bool
  notify: (Handler - NGINX Config) Run NGINX

- name: Ensure NGINX client body cache directories exist
  ansible.builtin.file:
    path: "{{ item.config.core.client_body_temp_path.path }}"
    state: directory
    owner: "{{ nginx_config_main_template.user | default('nginx') }}"
    mode: 0755
  loop: "{{ nginx_config_http_template }}"
  loop_control:
    label: "{{ item.config.core.client_body_temp_path.path | default('config.core.client_body_temp_path.path undefined') }}"
  when:
    - nginx_config_http_template_enable | bool
    - item.config.core.client_body_temp_path.path is defined

- name: Ensure NGINX proxy cache directories exist
  ansible.builtin.file:
    path: "{{ item.1.path }}"
    state: directory
    owner: "{{ nginx_config_main_template.user | default('nginx') }}"
    mode: 0755
  loop: "{{ nginx_config_http_template | subelements('config.proxy.cache_path', skip_missing=True) }}"
  loop_control:
    label: "{{ item.1.path | default('config.proxy.cache_path.path undefined') }}"
  when: nginx_config_http_template_enable | bool

- name: Ensure NGINX HTTP directory exists
  ansible.builtin.file:
    path: "{{ item.deployment_location | default('/etc/nginx/conf.d/') | dirname }}"
    state: directory
    mode: 0755
  loop: "{{ nginx_config_http_template }}"
  loop_control:
    label: "{{ item.deployment_location | default('/etc/nginx/conf.d/') | dirname }}"
  when: nginx_config_http_template_enable | bool

- name: Dynamically generate NGINX HTTP config files
  ansible.builtin.template:
    src: "{{ item.template_file | default('http/default.conf.j2') }}"
    dest: "{{ item.deployment_location | default('/etc/nginx/conf.d/default.conf') }}"
    backup: "{{ item.backup  | default(true) }}"
    mode: 0644
  loop: "{{ nginx_config_http_template }}"
  loop_control:
    label: "{{ item.deployment_location | default('/etc/nginx/conf.d/default.conf') }}"
  when: nginx_config_http_template_enable | bool
  notify: (Handler - NGINX Config) Run NGINX

- name: Dynamically generate NGINX stub status config file
  ansible.builtin.template:
    src: "{{ nginx_config_status_template_file | default('http/status.conf.j2') }}"
    dest: "{{ nginx_config_status_file_location | default('/etc/nginx/conf.d/status.conf') }}"
    backup: "{{ nginx_config_status_backup | default(true) }}"
    mode: 0644
  notify: (Handler - NGINX Config) Run NGINX
  when: nginx_config_status_enable | bool

- name: Dynamically generate NGINX API config file
  ansible.builtin.template:
    src: "{{ nginx_config_rest_api_template_file | default('http/api.conf.j2') }}"
    dest: "{{ nginx_config_rest_api_file_location | default('/etc/nginx/conf.d/api.conf') }}"
    backup: "{{ nginx_config_rest_api_backup | default(true) }}"
    mode: 0644
  notify: (Handler - NGINX Config) Run NGINX
  when: nginx_config_rest_api_enable | bool

- name: Ensure NGINX stream directory exists
  ansible.builtin.file:
    path: "{{ item.deployment_location | default('/etc/nginx/conf.d/') | dirname }}"
    state: directory
    mode: 0755
  loop: "{{ nginx_config_stream_template }}"
  loop_control:
    label: "{{ item.deployment_location | default('/etc/nginx/conf.d/') | dirname }}"
  when: nginx_config_stream_template_enable | bool

- name: Dynamically generate NGINX stream config files
  ansible.builtin.template:
    src: "{{ item.template_file | default('stream/default.conf.j2') }}"
    dest: "{{ item.deployment_location | default('/etc/nginx/conf.d/stream_default.conf') }}"
    backup: true
    mode: 0644
  loop: "{{ nginx_config_stream_template }}"
  loop_control:
    label: "{{ item.deployment_location | default('/etc/nginx/conf.d/stream_default.conf') }}"
  notify: (Handler - NGINX Config) Run NGINX
  when: nginx_config_stream_template_enable | bool
