---
- name: (CentOS/RHEL) Install dependencies
  ansible.builtin.yum:
    name:
      - libselinux-utils
      - policycoreutils
      - selinux-policy-targeted
  when: ansible_facts['os_family'] == "RedHat"

- name: Set SELinux mode to permissive
  ansible.posix.selinux:
    state: permissive
    policy: targeted
  when: not (ansible_check_mode and nginx_config_selinux_enforcing)

- name: Allow SELinux HTTP network connections
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  loop:
    - httpd_can_network_connect
    - httpd_can_network_relay

- name: Allow SELinux TCP connections on status ports
  community.general.seport:
    ports: "{{ nginx_config_status_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when: nginx_config_status_port is defined

- name: Allow SELinux TCP connections on Rest API ports
  community.general.seport:
    ports: "{{ nginx_config_rest_api_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when: nginx_config_rest_api_port is defined

- name: Allow SELinux TCP connections on specific ports
  community.general.seport:
    ports: "{{ nginx_config_selinux_tcp_ports }}"
    proto: tcp
    setype: http_port_t
    state: present
  when: nginx_config_selinux_tcp_ports is defined

- name: Allow SELinux UDP connections on specific ports
  community.general.seport:
    ports: "{{ nginx_config_selinux_udp_ports }}"
    proto: udp
    setype: http_port_t
    state: present
  when: nginx_config_selinux_udp_ports is defined

- name: Set SELinux mode to enforcing
  ansible.posix.selinux:
    state: enforcing
    policy: targeted
  when: nginx_config_selinux_enforcing
