---
- name: "Create NGINX config"
  debug:
    msg: "Creating NGINX config"
  when: nginx_config_debug_tasks | bool

- name: "Ensure HTML directory exists"
  file:
    path: "{{ item.value.html_file_location | default('/usr/share/nginx/html') }}"
    state: directory
    mode: 0755
  with_dict: "{{ nginx_config_html_demo_template }}"
  when: nginx_config_html_demo_template_enable | bool

- name: "Dynamically generate HTML files"
  template:
    src: "{{ item.value.template_file | default('www/index.html.j2') }}"
    dest: "{{ item.value.html_file_location | default('/usr/share/nginx/html') }}/{{ item.value.html_file_name | default('index.html') }}"
    backup: yes
    mode: 0644
  with_dict: "{{ nginx_config_html_demo_template }}"
  when: nginx_config_html_demo_template_enable | bool

- name: "Configure NGINX modules"
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: BOF
    line: "load_module {{ item }};"
  loop: "{{ nginx_config_modules }}"
  when:
    - nginx_config_modules is defined
    - nginx_config_modules | length > 0
  notify: "(Handler) Reload NGINX config"

- name: "Ensure NGINX main directory exists"
  file:
    path: "{{ nginx_config_main_template.conf_file_location | default('/etc/nginx') }}"
    state: directory
    mode: 0755
  when: nginx_config_main_template_enable | bool

- name: "Dynamically generate NGINX main configuration file"
  template:
    src: "{{ nginx_config_main_template.template_file | default('nginx.conf.j2') }}"
    dest: "{{ nginx_config_main_template.conf_file_location | default('/etc/nginx') }}/{{ nginx_config_main_template.conf_file_name | default('nginx.conf') }}"
    backup: yes
    mode: 0644
  when: nginx_config_main_template_enable | bool
  notify: "(Handler) Reload NGINX config"

- name: "Ensure NGINX HTTP directory exists"
  file:
    path: "{{ item.value.conf_file_location | default('/etc/nginx/conf.d/') }}"
    state: directory
    mode: 0755
  with_dict: "{{ nginx_config_http_template }}"
  when: nginx_config_http_template_enable | bool

- name: "Ensure NGINX proxy cache directories exist"
  file:
    path: "{{ item.1.path }}"
    state: directory
    owner: "{{ nginx_config_main_template.user | default('nginx') }}"
    mode: 0755
  with_subelements:
    - "{{ nginx_config_http_template }}"
    - proxy_cache.proxy_cache_path
    - skip_missing: true
  when: nginx_config_http_template_enable | bool

- name: "Dynamically generate NGINX HTTP config files"
  template:
    src: "{{ item.value.template_file | default('http/default.conf.j2') }}"
    dest: "{{ item.value.conf_file_location | default('/etc/nginx/conf.d/') }}/{{ item.value.conf_file_name | default('default.conf') }}"
    backup: yes
    mode: 0644
  with_dict: "{{ nginx_config_http_template }}"
  when: nginx_config_http_template_enable | bool
  notify: "(Handler) Reload NGINX config"

- name: "Dynamically generate NGINX stub status config file"
  template:
    src: "{{ nginx_config_status_template_file | default('http/status.conf.j2') }}"
    dest: "{{ nginx_config_status_file_location | default('/etc/nginx/conf.d/status.conf') }}"
    backup: yes
    mode: 0644
  notify: "(Handler) Reload NGINX config"
  when: nginx_config_status_enable | bool

- name: "Dynamically generate NGINX API config file"
  template:
    src: "{{ nginx_config_rest_api_template_file | default('http/api.conf.j2') }}"
    dest: "{{ nginx_config_rest_api_file_location | default('/etc/nginx/conf.d/api.conf') }}"
    backup: yes
    mode: 0644
  notify: "(Handler) Reload NGINX config"
  when: nginx_config_rest_api_enable | bool

- name: "Ensure NGINX stream directory exists"
  file:
    path: "{{ item.value.conf_file_location | default('/etc/nginx/conf.d/stream/') }}"
    state: directory
    mode: 0755
  with_dict: "{{ nginx_config_stream_template }}"
  when: nginx_config_stream_template_enable | bool

- name: "Dynamically generate NGINX stream config files"
  template:
    src: "{{ item.value.template_file | default('stream/default.conf.j2') }}"
    dest: "{{ item.value.conf_file_location | default('/etc/nginx/conf.d/stream/') }}/{{ item.value.conf_file_name | default('default.conf') }}"
    backup: yes
    mode: 0644
  with_dict: "{{ nginx_config_stream_template }}"
  notify: "(Handler) Reload NGINX config"
  when: nginx_config_stream_template_enable | bool

- name: "Create NGINX config"
  debug:
    msg: "Done creating NGINX config"
  when: nginx_config_debug_tasks | bool
